using Xamarin.Forms;
using Xamarin.Forms.Xaml;

[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
[assembly: ExportFont("fontello.ttf",Alias = "FA")]
[assembly: ExportFont("YsabeauOffice-Black.ttf",Alias = "Black")]
[assembly: ExportFont("YsabeauOffice-BlackItalic.ttf",Alias = "BlackItalic")]
[assembly: ExportFont("YsabeauOffice-Bold.ttf",Alias = "Bold")]
[assembly: ExportFont("YsabeauOffice-BoldItalic.ttf",Alias = "BoldItalic")]
[assembly: ExportFont("YsabeauOffice-ExtraBold.ttf",Alias = "ExtraBold")]
[assembly: ExportFont("YsabeauOffice-ExtraBoldItalic.ttf",Alias = "ExtraBoldItalic")]
[assembly: ExportFont("YsabeauOffice-ExtraLight.ttf",Alias = "ExtraLight")]
[assembly: ExportFont("YsabeauOffice-ExtraLightItalic.ttf",Alias = "ExtraLightItalic")]
[assembly: ExportFont("YsabeauOffice-Italic.ttf",Alias = "Italic")]
[assembly: ExportFont("YsabeauOffice-Light.ttf",Alias = "Light")]
[assembly: ExportFont("YsabeauOffice-LightItalic.ttf",Alias = "LightItalic")]
[assembly: ExportFont("YsabeauOffice-Medium.ttf",Alias = "Medium")]
[assembly: ExportFont("YsabeauOffice-MediumItalic.ttf",Alias = "MediumItalic")]
[assembly: ExportFont("YsabeauOffice-Regular.ttf",Alias = "Regular")]
[assembly: ExportFont("YsabeauOffice-SemiBold.ttf",Alias = "SemiBold")]
[assembly: ExportFont("YsabeauOffice-SemiBoldItalic.ttf",Alias = "SemiBoldItalic")]
[assembly: ExportFont("YsabeauOffice-Thin.ttf",Alias = "Thin")]
[assembly: ExportFont("YsabeauOffice-ThinItalic.ttf",Alias = "ThinItalic")]
